version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: install gcc
          command: apt-get update && apt-get install -y gcc
      - run:
          name: gcc version check
          command: echo `gcc --version`
      - run:
          name: compile
          command: |
            for dirname in */; do
              echo $dirname;
              cd $dirname;

              for files in *.c; do
                gcc -o ${files%.c}.out $files;
                echo ===========$'\n'$files compile is done$'\n'===========
                ./${files%.c}.out
                echo ===========$'\n'executed ${files%.c}.out$'\n'===========
                if [[ -e output.txt ]]; then
                  cat output.txt
                  echo ===========$'\n'this is output.txt$'\n'===========
                fi;
              done;

              cd ../
            done;
